// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	INTERVIEW: DurableObjectNamespace<import("./src/index").Interview>;
	AI: Ai;
}
