#:schema node_modules/wrangler/config-schema.json
name = "ai-interview-practice-tool"
main = "src/index.ts"
compatibility_date = "2024-11-06"

[assets]
directory = "public"

[observability]
enabled = true

[[durable_objects.bindings]]
name = "INTERVIEW"
class_name = "Interview"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Interview"]

[ai]
binding = "AI"
